### ISSUE TITLE
install error，I have uninstall lightgbm

### ISSUE THREAD

**Issue by DenceChen** [antmachineintelligence/mtgbmcode#1]
INFO:LightGBM:Starting to compile the library.
INFO:LightGBM:Starting to compile with CMake.
WARNING:LightGBM:Compilation failed.
INFO:LightGBM:Starting to compile with Homebrew OpenMP paths guesses.
WARNING:LightGBM:Compilation failed.
INFO:LightGBM:Starting to compile with MacPorts OpenMP paths guesses.
Traceback (most recent call last):
  File "setup.py", line 76, in silent_call
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/Users/zouyapeng/opt/anaconda3/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/zouyapeng/opt/anaconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '_lightgbm', '-j4']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 310, in <module>
    setup(name='lightgbmmt',
  File "/Users/zouyapeng/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/zouyapeng/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/zouyapeng/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/zouyapeng/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 267, in run
    compile_cpp(use_mingw=self.mingw, use_gpu=self.gpu, use_mpi=self.mpi,
  File "setup.py", line 198, in compile_cpp
    silent_call(["make", "_lightgbm", "-j4"], raise_error=True,
  File "setup.py", line 85, in silent_call
    raise Exception("\n".join((error_msg, LOG_NOTICE)))
Exception: An error has occurred while building lightgbm library file
The full version of error log was saved into /Users/zouyapeng/LightGBM_compilation.log

**Comment by mtgbmcode** [comment]
It seems you have a problem when compiling the cpp. You may fix the problem by checking the log /Users/zouyapeng/LightGBM_compilation.log.
Or you can send me the log here.
